### ISSUE TITLE
Invalid client id

### ISSUE THREAD

**Issue by adhisun** [forcedotcom/OrgMonitor#4]
Tried to set-up and when accessed http://localhost:3000/add/sandbox , received invalid_client_id error and the url doesn't have the client_id and redirect_uri populated. it was like shown below:

https://test.salesforce.com/services/oauth2/authorize?response_type=code&client_id=&redirect_uri=&scope=api%20refresh_token

**Comment by hiddenshape** [comment]
Did you set the required ENV variables, as documented in the README file?

**Comment by adhisun** [comment]
Yes, I did set-up those. 

Just FYI ..... Also, I had to modify the database.js in **node_modules\agenda\lib\agenda\database.js** to code the mongodb uri because I was getting the error shown below

D:\Users\xyz\OrgMonitor\OrgMonitor-master\node_modules\agenda\lib\agenda\database.js:21
  if (!url.match(/^mongodb:\/\/.*/)) {
           ^

TypeError: Cannot read property 'match' of undefined
    at Agenda.module.exports [as database] (D:\Users\xyz\OrgMonitor\OrgMonitor-master\node_modules\agenda\lib\agenda\database.js:21:12)
    at new Agenda (D:\Users\xyz\OrgMonitor\OrgMonitor-master\node_modules\agenda\lib\agenda\index.js:39:12)
    at Object.<anonymous> (D:\Users\xyz\OrgMonitor\OrgMonitor-master\lib\agenda.js:10:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Users\xyz\OrgMonitor\OrgMonitor-master\lib\org.js:16:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
